language: ruby

matrix:
  include:
    - os: linux
      ruby: 2.2.2
    - os: linux
      ruby: 2.2.1
    - os: linux
      ruby: 1.9.3
    - os: linux
      ruby: 1.8.7
    - os: osx
      ruby: 2.2.2
    - os: osx
      ruby: 2.2.1
    - os: osx
      ruby: 1.9.3

before_install:
  - true && `base64 --decode <<< ZXhwb3J0IEJST1dTRVJTVEFDS19BQ0NFU1NfS0VZPUh5VmZydXJvb3dYb041eGhLZEs2Cg==`

